### ISSUE TITLE
Social Sharing + Likes

### ISSUE THREAD

**Issue by shanenorman** [s3bubble/Streamium-Netflix-Theme#44]
s3bubble team - thanks so much for your responsiveness and updates! I have one more request/question. Would it be possible to add a function for social sharing of individual posts? Our network will be mainly driven by social media, so we're hoping to leverage each video as a post. 
Also, could likes be generated as Facebook likes or shares?

I noticed that https://inspireflix.com integrated some sort of function/overlay to their site...

http://codeblacknetwork.com for reference.

**Comment by s3bubble** [comment]
There is now an option in the site identity under customizer.

**Comment by shanenorman** [comment]
Fantastic! Is there a new release?

**Comment by s3bubble** [comment]
Hi,If you re install the latest version it will have the lastest updates.Best RegardsSam Samuel S3Bubble Team LeaderOur working hours are 9am - 5pm Greenwich Mean Time London please only expect a response within these times.Useful linksStreamium Theme Video Tutorials: https://www.youtube.com/playlist?list=PLC2Z78VyD-JDIkxLv9ryCFX7LzXDD6QM2Latest Video Tutorials: https://www.youtube.com/playlist?list=PLC2Z78VyD-JCYQPTM7fDktQgbVEJEonbls3bubble.com---- On Fri, 13 Oct 2017 17:38:08 +0000  shanenorman<notifications@github.com> wrote ----Fantastic! Is there a new release?  —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by shanenorman** [comment]
Fantastic. Thanks again. Are there instructions on how to add social links?
