### ISSUE TITLE
Video cover image not showing

### ISSUE THREAD

**Issue by phemmywales** [s3bubble/Streamium-Netflix-Theme#55]
Hi

I just signed up for a Trial of S3Bubble service, I have installed the Streamium Wordpress theme following the Video tutorials. After importing the Demo data,  the video Cover image/thumbnails are not showing on the site, i have recreated the site site afresh three times but still same result. I have also tried to work with the demo content by add new video post and linking to content in S3Bubble Account but still got same result. i would like to know if this is a restriction with the trial service or there is something else responsible. Just to note, the wordpress site is hosted on Azure and i am using Streamium theme version 17.38

Regards

**Comment by phemmywales** [comment]
Thank you for your response.

The site url has been configured in S3 Bubble and I already have two videos in my S3Bubble account.  surprisingly, the video plays (though player customization done in S3 not showing up too) when you select the video on the Carousel. How do it send the URL and Login details

**Comment by s3bubble** [comment]
Hi Phemmywales,Just send us your S3Bubble username I can get your url from there.In your WordPress website go to users create an admin user.Username: s3bubbleEmail: support@s3bubble.comWe will then receive the info and can check your full setup in around an hours time you can then delete us from your users.Best RegardsSam Samuel S3Bubble Team LeaderOur working hours are 9am - 5pm Greenwich Mean Time London please only expect a response within these times.Useful linksStreamium Theme Video Tutorials: https://www.youtube.com/playlist?list=PLC2Z78VyD-JDIkxLv9ryCFX7LzXDD6QM2Latest Video Tutorials: https://www.youtube.com/playlist?list=PLC2Z78VyD-JCYQPTM7fDktQgbVEJEonbls3bubble.com---- On Wed, 14 Feb 2018 13:52:05 +0000  phemmywales<notifications@github.com> wrote ----Thank you for your response. The site url has been configured in S3 Bubble and I already have two videos in my S3Bubble account.  surprisingly, the video plays (though player customization done in S3 not showing up too) when you select the video on the Carousel. How do it send the URL and Login details  —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by phemmywales** [comment]
S3 Bubble Username - phemmy

**Comment by phemmywales** [comment]
Hi

I hope you have received email about the wordpress account

**Comment by s3bubble** [comment]
Hi Phemmywales,We only received your username and no WordPress login.We did take a quick look at your setup and there is definitely some weird issues that we will need to take a look at.The urls paths are strange and if you view source some of your urls are appended ://png are you using a server side cache plugin or another plugin that would alter the default paths.Best RegardsSam Samuel S3Bubble Team LeaderOur working hours are 9am - 5pm Greenwich Mean Time London please only expect a response within these times.Useful linksStreamium Theme Video Tutorials: https://www.youtube.com/playlist?list=PLC2Z78VyD-JDIkxLv9ryCFX7LzXDD6QM2Latest Video Tutorials: https://www.youtube.com/playlist?list=PLC2Z78VyD-JCYQPTM7fDktQgbVEJEonbls3bubble.com---- On Thu, 15 Feb 2018 16:50:02 +0000  phemmywales<notifications@github.com> wrote ----Hi I hope you have received email about the wordpress account  —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by phemmywales** [comment]
Thank you for getting back to me, for some reason my word press is not sending out email b y default. I had to install an SMTP plugin

There is  no Server side caching installed. Only the required plugin, woo, file manager and woocommerce

Please confirm receipt of Account email


Thanks

**Comment by phemmywales** [comment]
Hi

Please i am still awaiting you response

Regards

**Comment by phemmywales** [comment]
I have taking time to start a fresh wordpress install. Images uploaded after the fresh install got uploaded properly and were showing on the page. Then i uploaded streamium template version 17.19, installed the required plugin and then tried to create a new post and upload new image. Image was upload but wordpress generated this URL /wp-content/uploads/2018/02/avengeri.jpg:// which is wrong and different from the normal URL that i got with the upload before streamium theme was installed. It show now that the Streamium theme is responsible for this issue. i will appreciate your earliest response.


Regards

**Comment by phemmywales** [comment]
Hi

I was able to resolve the issue, it wasnt a problem from the Theme as i suggested in my last post. It was some line of code in the wp-config file that causing the issue i guess was set during the deployment of Wordpress instance in Azure. here is the code
---
//Relative URLs for swapping across app service deployment slots 
define('WP_HOME', 'http://'. filter_input(INPUT_SERVER, 'HTTP_HOST', FILTER_SANITIZE_STRING));
define('WP_SITEURL', 'http://'. filter_input(INPUT_SERVER, 'HTTP_HOST', FILTER_SANITIZE_STRING));
define('WP_CONTENT_URL', '/wp-content');
define('DOMAIN_CURRENT_SITE', filter_input(INPUT_SERVER, 'HTTP_HOST', FILTER_SANITIZE_STRING));

The site is now functioning properly.

Thank you

**Comment by s3bubble** [comment]
Hi @phemmywales 

Thanks for the info and glad you are up and running hopefully this can help any other users if this issue arises again.

Best Regards

Sam

**Comment by phemmywales** [comment]
I am glad we were able to resolve it. You are definitely going to be seeing more of me

You have just solved my two year old problem of getting our platform started

Regards
