### ISSUE TITLE
Categories Not Working After Update of "Movie Options" in Customizer

### ISSUE THREAD

**Issue by Zetsunawa** [s3bubble/Streamium-Netflix-Theme#84]
I changed the name of the category from Movies to Videos, now when I click the link to the category I get a 404 page.

I updated the permalinks but it didn't help. nor did changing the category name/taxonomy back to Movies.

**Comment by jdphiladelphia** [comment]
Hi @Zetsunawa - 

Do you have one singular and the other plural?

Example:
![image](https://user-images.githubusercontent.com/24858286/38177718-8c8b310a-35d3-11e8-9d8a-6bfeb6051bc2.png)

They cannot be both plural, and they cannot both be singular.

Hope that helps!  If not, then I have no idea since you already resaved permalinks - we'll have to wait for S3Bubble to respond :)

P.S. Don't work too hard on a weekend, a holiday weekend at that.

Regards,
JD

**Comment by Zetsunawa** [comment]
Yeah, I have them as different names (one plural and one singular)

**Comment by Zetsunawa** [comment]
It was a plugin conflict.

**Comment by jdphiladelphia** [comment]
@Zetsunawa , ah. So glad you figured it out!

**Comment by s3bubble** [comment]
Thanks for the updates
